server:
  port: 10010
spring:
  application:
    name: wlkg-api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
  ignored-patterns: /upload/**
  ignored-services:
   - upload-service # 忽略upload-service服务
  add-host-header: true   #携带请求本身的host头信息
  sensitive-headers:  #禁止使用的头信息，设置为null,否则set-cooike无效

ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 10000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 熔断超时时长：10000ms

wlkg:
  jwt:
    pubKeyPath:  D:/tmp/rsa/rsa.pub # 公钥地址
    cookieName: WLKG_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
